variables:
  GIT_DEPTH: 0
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "33.0.1"

  # It's what version of the command line tools we're going to download from the official site.
  # Official Site-> https://developer.android.com/studio/index.html
  # There, look down below at the cli tools only, sdk tools package is of format:
  #        commandlinetools-os_type-ANDROID_SDK_TOOLS_latest.zip
  # when the script was last modified for latest compileSdkVersion, it was which is written down below
  ANDROID_SDK_TOOLS: "9123335"

stages:
    - build

build_badges:
  stage: build
  image: python:3.6.6
  before_script:
    - apt-get update -qy
    - pip install anybadge
    - chmod +x get-updated-badge-info.sh
  script:
    - echo "Some script to build your code"
  after_script:
    - ./get-updated-badge-info.sh
  artifacts:
    paths:
        - badges.json
        - badges
    when: always

assembleDebug:
  image: seanghay/android-ci
  stage: build
  before_script:
    - chmod +x ./gradlew
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script:
    - gradle wrapper
    - ./gradlew assembleDebug
    - cp app/build/outputs/apk/debug/app-debug.apk app-debug.apk
  artifacts:
    paths:
      - app-debug.apk